Selenium- US 4 & testng
ScottKainos/GothicLlamasFE pull request #43
Opened 2021-09-06 15:06 UTC by ScottKainos

- Changed selenium tests to run using testng (allows them to be run together in a suite)
- - added selenium tests for US 4
- - split selenium tests for US 2

2021-09-06 15:27 UTC, reespozzi requested changes

2021-09-06 15:27 UTC, reespozzi commented on selenium_test/src/main/java/us_selenium_test/framework/FunctionalTestFirefox.java
> +import org.openqa.selenium.edge.EdgeDriver;
Do we need all of these other browser imports in the Firefox class and any other browser specific classes?

2021-09-07 07:48 UTC, sylwia-luczak commented
I accept all changes and give my approval.

2021-09-07 07:49 UTC, sylwia-luczak approved these changes
I accept all changes and give my approval.

2021-09-07 08:25 UTC, reespozzi approved these changes

2021-09-07 08:27 UTC, merged